[install]
# Use the exact versions specified in package.json
exact = true

[test]
# Use the Jest-compatible test runner
testRegex = "\\.(test|spec)\\.[jt]sx?$"

[debug]
# Enable source maps for debugging
sourcemap = true

